### PR TITLE
icon working on shell page, Person Info Page added, functions working…

### PR DESCRIPTION
**Pull request by studentPaulStuart**
Merging the Personal Info Page with the rest of the Project. Needs testing and review

### CODE REVIEW

**Comment by doubleedesign** [comment]
Hey @studentPaulStuart, code looks good at first glance but when I try to actually run it I'm getting some errors: This is when running on "local machine" as x64. Happens on x86 as well but not as many. Should I be running it under a different configuration, or am I maybe missing something you're doing to run it? 

image

**Comment by studentPaulStuart** [comment]
@doubleedesign that is interesting, that was precisely the issue I was having for last week and a half. I only just fixed it now after looking at KT's code. I just did a sync and ran it again.

Did you do a clean and rebuild?

**Comment by doubleedesign** [comment]
Thanks @studentPaulStuart, clean and rebuild almost fixes it! I just get it in one spot now:

image

**Comment by studentPaulStuart** [comment]
@doubleedesign 
OK, looks it definitively is some sort of build issue when ever there is a sync or a push to GitHub. I'm currently looking at some of these solutions but a lot are quite old. A couple of things;

1. Right click on solution, restore nuGet packages
2. Delete the Bin and Obj local folders then do a rebuild
3. Right click on Start Finance App > properties and switch the target version of windows under Application
4. Also in properties check the Debug buttons for uninstall and then re-install packages and Deploy optional packages
5. https://stackoverflow.com/questions/450999/are-you-missing-an-assembly-reference-compile-error-visual-studio

**Comment by studentPaulStuart** [comment]
@doubleedesign Also do a another sync with the remote branch I did some re-configuring and just pushed so it might do all this automatically if you run it again.

**Comment by doubleedesign** [comment]
Sadly none of those suggestions fixed it completely @studentPaulStuart so I did some digging and found that MainPageViewModel's namespace was set to Views not ViewModels and updating the line of code causing the error to Views resolved that. However, the application still didn't compile because you had Click events without the handlers written, so I've just added stubs for those so the application now compiles for me. 

My commits to your branch didn't get added to this pull request because I made them, so I've requested your review of [my PR](https://github.com/studentPaulStuart/Tafe21S204/pull/21) because I figure we should make sure my fixes don't break things for you before we merge anything. :)

**Comment by studentPaulStuart** [comment]
@doubleedesign I know what the issue is. There are 2 branches of same thing. I deleted the old branch '**peroninfo**' and made a new one '**PersonalInfo**' which is correct and will work. But I didn't realize we are all collaborators so you would have had a local copy and it probably then got pushed back to git hub. 

So we all need to delete anything on our computers called personinfo branch and download the personalInfo new branch

**Pull request closed without merging**
