### PR TITLE
Add model + start UI for Appointments

### PR DESCRIPTION
**Pull request by doubleedesign**

### CODE REVIEW

**Comment by Bastiann24** [comment]
Hello Leesa,
I just tested your pull request and it works 100% for me. I would suggest to create the "AppointmentsPage.xaml" and "AppointmentsPage.xaml.cs" together, as you are creating the .xaml.cs file as a c# file and you might present some issues (this happened to me). Image for reference
Capture2
Everything else works very good :) Well done!
I'll wait for your comments to close and approve this pull request. Thank you!

**Comment by Bastiann24** [comment]
Hello Leesa,
I just tested your pull request and it works 100% for me. I would suggest to create the "AppointmentsPage.xaml" and "AppointmentsPage.xaml.cs" together, as you are creating the .xaml.cs file as a c# file and you might present some issues (this happened to me). Image for reference
Capture2
Everything else works very good :) Well done!
I'll wait for your comments to close and approve this pull request. Thank you!

**Comment by Bastiann24** [comment]
This is what I meant with creating it together, when you go to add new item under "Views" folder, click on XAML located on the left ponel and then select Blank Page template and rename it, this will automatically create the XAML file and XAML.cs file together. Hope it helps! 
Capture3

**Comment by doubleedesign** [comment]
Oh thanks @Bastiann24! I did have some weird behaviour with code formatting that this possibly explains.

**Review by Bastiann24 — COMMENTED** [review]
All good now:)

**Pull request merged**
